/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrapeGachaRouteImport } from './routes/scrape-gacha'
import { Route as IndexRouteImport } from './routes/index'

const ScrapeGachaRoute = ScrapeGachaRouteImport.update({
  id: '/scrape-gacha',
  path: '/scrape-gacha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scrape-gacha': typeof ScrapeGachaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scrape-gacha': typeof ScrapeGachaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scrape-gacha': typeof ScrapeGachaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scrape-gacha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scrape-gacha'
  id: '__root__' | '/' | '/scrape-gacha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScrapeGachaRoute: typeof ScrapeGachaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scrape-gacha': {
      id: '/scrape-gacha'
      path: '/scrape-gacha'
      fullPath: '/scrape-gacha'
      preLoaderRoute: typeof ScrapeGachaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScrapeGachaRoute: ScrapeGachaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
