/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScrapeGachaRouteImport } from './routes/api/scrape-gacha'
import { Route as ApiGachaGamesIndexRouteImport } from './routes/api/gacha-games/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeGachaRoute = ApiScrapeGachaRouteImport.update({
  id: '/api/scrape-gacha',
  path: '/api/scrape-gacha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGachaGamesIndexRoute = ApiGachaGamesIndexRouteImport.update({
  id: '/api/gacha-games/',
  path: '/api/gacha-games/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/scrape-gacha': typeof ApiScrapeGachaRoute
  '/api/gacha-games': typeof ApiGachaGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/scrape-gacha': typeof ApiScrapeGachaRoute
  '/api/gacha-games': typeof ApiGachaGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/scrape-gacha': typeof ApiScrapeGachaRoute
  '/api/gacha-games/': typeof ApiGachaGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/scrape-gacha' | '/api/gacha-games'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/scrape-gacha' | '/api/gacha-games'
  id: '__root__' | '/' | '/api/scrape-gacha' | '/api/gacha-games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiScrapeGachaRoute: typeof ApiScrapeGachaRoute
  ApiGachaGamesIndexRoute: typeof ApiGachaGamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-gacha': {
      id: '/api/scrape-gacha'
      path: '/api/scrape-gacha'
      fullPath: '/api/scrape-gacha'
      preLoaderRoute: typeof ApiScrapeGachaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gacha-games/': {
      id: '/api/gacha-games/'
      path: '/api/gacha-games'
      fullPath: '/api/gacha-games'
      preLoaderRoute: typeof ApiGachaGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiScrapeGachaRoute: ApiScrapeGachaRoute,
  ApiGachaGamesIndexRoute: ApiGachaGamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
